export enum SpendCategory {
  GROCERIES = 'groceries',
  DINING = 'dining',
  GAS = 'gas',
  TRAVEL = 'travel',
  HOTELS = 'hotels',
  AIRLINES = 'airlines',
  ENTERTAINMENT = 'entertainment',
  SHOPPING = 'shopping',
  ONLINE_SHOPPING = 'online_shopping',
  STREAMING = 'streaming',
  PHARMACY = 'pharmacy',
  UTILITIES = 'utilities',
  TRANSIT = 'transit',
  PHONE = 'phone',
  OFFICE_SUPPLIES = 'office_supplies',
  FITNESS = 'fitness',
  WHOLESALE = 'wholesale',
  OTHER = 'other',
}

export const MCC_TO_CATEGORY: Record<string, SpendCategory> = {
  '5411': SpendCategory.GROCERIES,
  '5422': SpendCategory.GROCERIES,
  '5441': SpendCategory.GROCERIES,
  '5451': SpendCategory.GROCERIES,
  '5462': SpendCategory.GROCERIES,
  '5812': SpendCategory.DINING,
  '5813': SpendCategory.DINING,
  '5814': SpendCategory.DINING,
  '5541': SpendCategory.GAS,
  '5542': SpendCategory.GAS,
  '5983': SpendCategory.GAS,
  '3000': SpendCategory.AIRLINES,
  '3001': SpendCategory.AIRLINES,
  '3002': SpendCategory.AIRLINES,
  '3003': SpendCategory.AIRLINES,
  '3004': SpendCategory.AIRLINES,
  '3005': SpendCategory.AIRLINES,
  '3006': SpendCategory.AIRLINES,
  '3007': SpendCategory.AIRLINES,
  '3008': SpendCategory.AIRLINES,
  '3009': SpendCategory.AIRLINES,
  '3010': SpendCategory.AIRLINES,
  '3011': SpendCategory.AIRLINES,
  '3012': SpendCategory.AIRLINES,
  '3501': SpendCategory.HOTELS,
  '3502': SpendCategory.HOTELS,
  '3503': SpendCategory.HOTELS,
  '3504': SpendCategory.HOTELS,
  '3509': SpendCategory.HOTELS,
  '7011': SpendCategory.HOTELS,
  '7832': SpendCategory.ENTERTAINMENT,
  '7922': SpendCategory.ENTERTAINMENT,
  '7994': SpendCategory.ENTERTAINMENT,
  '7996': SpendCategory.ENTERTAINMENT,
  '7998': SpendCategory.ENTERTAINMENT,
  '5311': SpendCategory.SHOPPING,
  '5331': SpendCategory.SHOPPING,
  '5399': SpendCategory.SHOPPING,
  '5651': SpendCategory.SHOPPING,
  '5691': SpendCategory.SHOPPING,
  '5942': SpendCategory.SHOPPING,
  '5970': SpendCategory.ONLINE_SHOPPING,
  '5999': SpendCategory.ONLINE_SHOPPING,
  '4899': SpendCategory.STREAMING,
  '7841': SpendCategory.STREAMING,
  '5122': SpendCategory.PHARMACY,
  '5912': SpendCategory.PHARMACY,
  '4900': SpendCategory.UTILITIES,
  '4111': SpendCategory.TRANSIT,
  '4112': SpendCategory.TRANSIT,
  '4119': SpendCategory.TRANSIT,
  '4121': SpendCategory.TRANSIT,
  '4131': SpendCategory.TRANSIT,
  '4784': SpendCategory.TRANSIT,
  '4814': SpendCategory.PHONE,
  '4816': SpendCategory.PHONE,
  '5943': SpendCategory.OFFICE_SUPPLIES,
  '5111': SpendCategory.OFFICE_SUPPLIES,
  '7997': SpendCategory.FITNESS,
  '5300': SpendCategory.WHOLESALE,
  '5309': SpendCategory.WHOLESALE,
  '5310': SpendCategory.WHOLESALE,
};

export function categorizeByMCC(mccCode: string | null | undefined): SpendCategory | null {
  if (!mccCode) return null;
  return MCC_TO_CATEGORY[mccCode] || null;
}

export const CATEGORY_LABELS: Record<SpendCategory, string> = {
  [SpendCategory.GROCERIES]: 'Groceries',
  [SpendCategory.DINING]: 'Dining',
  [SpendCategory.GAS]: 'Gas',
  [SpendCategory.TRAVEL]: 'Travel',
  [SpendCategory.HOTELS]: 'Hotels',
  [SpendCategory.AIRLINES]: 'Airlines',
  [SpendCategory.ENTERTAINMENT]: 'Entertainment',
  [SpendCategory.SHOPPING]: 'Shopping',
  [SpendCategory.ONLINE_SHOPPING]: 'Online Shopping',
  [SpendCategory.STREAMING]: 'Streaming Services',
  [SpendCategory.PHARMACY]: 'Pharmacy',
  [SpendCategory.UTILITIES]: 'Utilities',
  [SpendCategory.TRANSIT]: 'Transit',
  [SpendCategory.PHONE]: 'Phone & Internet',
  [SpendCategory.OFFICE_SUPPLIES]: 'Office Supplies',
  [SpendCategory.FITNESS]: 'Fitness',
  [SpendCategory.WHOLESALE]: 'Wholesale Clubs',
  [SpendCategory.OTHER]: 'Other',
};
